version: '3'
services:
  kafka:
    image: vepo/kafka:3.4.0
    ports:
     - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'true'
  schema-registry:
    image: apicurio/apicurio-registry-mem:2.3.1.Final
    ports:
      - 8081:8080
    depends_on:
      - kafka
  position-server:
    build:
      context: ./position-server
    ports:
      - 8080:8080
    volumes:
      - ./position-server:/app
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - kafka
      - schema-registry