version: '3'
services:
  kafka:
    image: vepo/kafka:3.4.0
    ports:
     - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  position-server:
    build:
      context: ./position-server
    depends_on:
      - kafka